---
- hosts: localhost
  tasks:
    - name: Add disks to virtual machine
      vmware_guest_disk:
        hostname: "10.9.19.204"
        datacenter: "technet-asia.com"
        validate_certs: no
        name: "{{ vm_name }}"
        disk:
          - size_gb: {{ add_disk_size }}
            type: thin
            datastore: vmstorei02
            state: present
            scsi_controller: 0
            unit_number: 1
      delegate_to: localhost
      register: disk_facts
      when: check_add_disk == "t"