---
- hosts: localhost
  tasks:
    - name: Add guest NIC
      vmware_guest_network:
        hostname: "10.9.19.204"
        datacenter: "technet-asia.com"
        validate_certs: no
        name: "{{ vm_name }}"
        gather_network_info: false
        networks:
          - name: "PG_ICO_Infra_MGM"
            state: new
      delegate_to: localhost
      when: num_network_adapters == 2
