- hosts: all
  tasks:
    - name: install httpd-pod on openshift
      shell: /usr/local/bin/oc create -f /oc_yaml/httpd-pod.yaml
    - name: install httpd-svc on openshift
      shell: /usr/local/bin/oc create -f /oc_yaml/httpd-svc.yaml