- hosts: all
  roles:
     - poc2vm
  vars:
    ipcount: 0
  tasks:
     - name: Set Varible
       set_fact:
         ipcount: "{{ 0 if ({{prj}} == 'CAP') }}"
       set_fact:
         ipcount: "{{ 3 if ({{prj}} == 'FO') }}"
       set_fact:
         ipcount: "{{ 6 if ({{prj}} == 'ITGW') }}"
