- hosts: all
  roles:
     - poc2vm
  vars:
    ipcount: 0
  tasks:
     - name: Set Varible
       set_fact:
         ipcount: "{{ 0 if ({{prj}} == 'CAP') else {{ 3 if ({{prj}} == 'FO') else 6 }} }}"
