- name: Terraform apply template
  template:
    src: prod-2vm-stack.tf
    dest: /terraform/stacks/{{prj}}/prod-vm-stack.tf
    remote_src: true
- name: Terraform apply template
    shell: echo "yes" | /terraform/terraform apply
    args:
      chdir: /terraform/stacks/{{prj}}
